### ISSUE TITLE
Unnecessary TCC Repo Files

### ISSUE THREAD

**Issue by dougbrn** [UWMRO/TCS#19]
- **bct_original(folder)**: The source files for the bct telescope drivers, these should be stored on Analysis and don't need to be stored on the public repo.
- **gimg (folder)**: These were just placeholder images Joe uploaded for the guider tab. This can be deleted, but I'd remove the reference to it in the code (TCC frame class, ctrl-F img_default) as well.
- **AddLinearSpacer.py**: Example wxpython code Tristan uploaded at some point, this can be deleted. May be worth saving this on Analysis.
- **TCC_parser.py**: A remnant of the original twisted python server effort. This can be deleted.
- **TCC_server.py**: The original first effort at a twisted python server for the TCC. This can be removed from the repo. May be worth saving this on Analysis in the event the AUEG wants to try their hand at swig.
- **alta_2.cpp**: Joe's sample C++ code for the ALTA camera control at APO, completely referential and can be removed from the repo.
- **autoNightV2.py**: Early on night log reference code provided by Joe. This can be deleted. Might be worthwhile to save on Analysis since there is more to do on the night log for Bifrost.
- **listener.cpp**: First draft of a C++ telnet server that can be connected to via twisted. Can be removed.
- **twistTest.py**: A generic twisted python server to mold into a TCC specific server. Can be removed.
- **parsercode/listener.cpp**: Same as **listener.cpp**
- **parsercode/parser.cpp**: Originally the parser was going to be a separate file from the server (**TCCserver.cpp**), but the parser was eventually built into the server directly for simplicity. Can be removed.
- **parsercode/twistTest.py**: Same as **twistTest.cpp**

**Comment by dougbrn** [comment]
Hi folks, here's a github issue addressing some repo cleanup I would recommend doing. Feel free to tack on more comments or questions about repo cleanup on this issue.

**Comment by ojf** [comment]
followed Doug's suggestions in the initial commits in the Repo-cleanup branch:

- **AddLinearSpacer.py**: deleted.
- **bct_original(folder)**: duplicate files removed, moved inside bct folder.
- **gimg (folder)**: deleted, but still need to remove the reference to it in the code (TCC frame class, ctrl-F img_default) as well. Code should tolerate missing file if it doesn't...
- **alta_2.cpp**: deleted
- **autoNightV2.py**: deleted
- **listener.cpp**: deleted this copy, kept identical file in parsercode/
- **twistTest.py**: deleted this copy, kept identical file in parsercode/

**Comment by ojf** [comment]
- **TCC_parser.py**, **TCCserver.cpp**, **TCCserver.py**: moved to parsercode/originals/

**Comment by ojf** [comment]
Latest Repo cleanup (commits on May 10th) closes this issue
